# Generated by Django 5.2.4 on 2025-07-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_address_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='building',
        ),
        migrations.RemoveField(
            model_name='address',
            name='demophone_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='floor',
        ),
        migrations.AddField(
            model_name='address',
            name='get_phone',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='google_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
