# Generated by Django 5.2.4 on 2025-07-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
